-- PLL_125_to_50.vhd

-- Generated using ACDS version 18.1 222

library IEEE;
library altera_iopll_181;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity PLL_125_to_50 is
	port (
		rst      : in  std_logic := '0'; --   reset.reset
		refclk   : in  std_logic := '0'; --  refclk.clk
		locked   : out std_logic;        --  locked.export
		outclk_0 : out std_logic         -- outclk0.clk
	);
end entity PLL_125_to_50;

architecture rtl of PLL_125_to_50 is
	component PLL_125_to_50_altera_iopll_181_ohkdwzi_cmp is
		port (
			rst      : in  std_logic := 'X'; -- reset
			refclk   : in  std_logic := 'X'; -- clk
			locked   : out std_logic;        -- export
			outclk_0 : out std_logic         -- clk
		);
	end component PLL_125_to_50_altera_iopll_181_ohkdwzi_cmp;

	for iopll_0 : PLL_125_to_50_altera_iopll_181_ohkdwzi_cmp
		use entity altera_iopll_181.PLL_125_to_50_altera_iopll_181_ohkdwzi;
begin

	iopll_0 : component PLL_125_to_50_altera_iopll_181_ohkdwzi_cmp
		port map (
			rst      => rst,      --   reset.reset
			refclk   => refclk,   --  refclk.clk
			locked   => locked,   --  locked.export
			outclk_0 => outclk_0  -- outclk0.clk
		);

end architecture rtl; -- of PLL_125_to_50
