//Declaring wires.
wire George_P, George_N, Ruth_P, Ruth_N, Hans_P, Hans_N, Tracy_P, Tracy_N, Ethan_P, Ethan_N
//FMC pin mapping for Randy FPGA.
assign George_P = FMC1_CLK_M2C_P[0]; //Direction: Input
assign FMC1_CLK_M2C_N[0] = George_N; //Direction: Output
assign FMC1_LA_P[2] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[2] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[4] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[4] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[7] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[7] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[11] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[11] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[15] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[15] = 1'bz; //Direction: Unused, High Impedance
assign Ruth_P = FMC1_LA_P[19]; //Direction: Input
assign FMC1_LA_N[19] = Ruth_N; //Direction: Output
assign FMC1_LA_P[21] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[21] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[24] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[24] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[28] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[28] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[30] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[30] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[32] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[32] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_CLK_M2C_P[1] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_CLK_M2C_N[1] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[0] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[0] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[3] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[3] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[8] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[8] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[12] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[12] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[16] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[16] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[20] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[20] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[22] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[22] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[25] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[25] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[29] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[29] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[31] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[31] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[33] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[33] = 1'bz; //Direction: Unused, High Impedance
assign Hans_P = FMC1_GBTCLK_M2C_P[0]; //Direction: Input
assign FMC1_GBTCLK_M2C_N[0] = Hans_N; //Direction: Output
assign FMC1_LA_P[1] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[1] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[5] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[5] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[9] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[9] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[13] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[13] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[17] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[17] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[23] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[23] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[26] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[26] = 1'bz; //Direction: Unused, High Impedance
assign Tracy_P = FMC1_DP_C2M_P[0]; //Direction: Input
assign FMC1_DP_C2M_N[0] = Tracy_N; //Direction: Output
assign Ethan_P = FMC1_DP_M2C_P[0]; //Direction: Input
assign FMC1_DP_M2C_N[0] = Ethan_N; //Direction: Output
assign FMC1_LA_P[6] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[6] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[10] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[10] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[14] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[14] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[18] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[18] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_P[27] = 1'bz; //Direction: Unused, High Impedance
assign FMC1_LA_N[27] = 1'bz; //Direction: Unused, High Impedance
