// test_nco.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module test_nco (
		input  wire        clk,       // clk.clk
		input  wire        reset_n,   // rst.reset_n
		input  wire        clken,     //  in.clken
		input  wire [31:0] phi_inc_i, //    .phi_inc_i
		output wire [17:0] fsin_o,    // out.fsin_o
		output wire        out_valid  //    .out_valid
	);

	test_nco_altera_nco_ii_181_4lk2jgi nco_ii_0 (
		.clk       (clk),       //   input,   width = 1, clk.clk
		.reset_n   (reset_n),   //   input,   width = 1, rst.reset_n
		.clken     (clken),     //   input,   width = 1,  in.clken
		.phi_inc_i (phi_inc_i), //   input,  width = 32,    .phi_inc_i
		.fsin_o    (fsin_o),    //  output,  width = 18, out.fsin_o
		.out_valid (out_valid)  //  output,   width = 1,    .out_valid
	);

endmodule
