-- FIFO.vhd

-- Generated using ACDS version 18.1 222

library IEEE;
library fifo_181;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIFO is
	port (
		data    : in  std_logic_vector(56 downto 0) := (others => '0'); --  fifo_input.datain
		wrreq   : in  std_logic                     := '0';             --            .wrreq
		rdreq   : in  std_logic                     := '0';             --            .rdreq
		wrclk   : in  std_logic                     := '0';             --            .wrclk
		rdclk   : in  std_logic                     := '0';             --            .rdclk
		q       : out std_logic_vector(56 downto 0);                    -- fifo_output.dataout
		rdempty : out std_logic;                                        --            .rdempty
		wrfull  : out std_logic                                         --            .wrfull
	);
end entity FIFO;

architecture rtl of FIFO is
	component FIFO_fifo_181_73iislq_cmp is
		port (
			data    : in  std_logic_vector(56 downto 0) := (others => 'X'); -- datain
			wrreq   : in  std_logic                     := 'X';             -- wrreq
			rdreq   : in  std_logic                     := 'X';             -- rdreq
			wrclk   : in  std_logic                     := 'X';             -- wrclk
			rdclk   : in  std_logic                     := 'X';             -- rdclk
			q       : out std_logic_vector(56 downto 0);                    -- dataout
			rdempty : out std_logic;                                        -- rdempty
			wrfull  : out std_logic                                         -- wrfull
		);
	end component FIFO_fifo_181_73iislq_cmp;

	for fifo_0 : FIFO_fifo_181_73iislq_cmp
		use entity fifo_181.FIFO_fifo_181_73iislq;
begin

	fifo_0 : component FIFO_fifo_181_73iislq_cmp
		port map (
			data    => data,    --  fifo_input.datain
			wrreq   => wrreq,   --            .wrreq
			rdreq   => rdreq,   --            .rdreq
			wrclk   => wrclk,   --            .wrclk
			rdclk   => rdclk,   --            .rdclk
			q       => q,       -- fifo_output.dataout
			rdempty => rdempty, --            .rdempty
			wrfull  => wrfull   --            .wrfull
		);

end architecture rtl; -- of FIFO
