-- PLL_main.vhd

-- Generated using ACDS version 18.1 222

library IEEE;
library altera_iopll_181;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity PLL_main is
	port (
		rst      : in  std_logic := '0'; --   reset.reset
		refclk   : in  std_logic := '0'; --  refclk.clk
		outclk_0 : out std_logic;        -- outclk0.clk
		outclk_1 : out std_logic         -- outclk1.clk
	);
end entity PLL_main;

architecture rtl of PLL_main is
	component PLL_main_altera_iopll_181_qm7lbwq_cmp is
		port (
			rst      : in  std_logic := 'X'; -- reset
			refclk   : in  std_logic := 'X'; -- clk
			outclk_0 : out std_logic;        -- clk
			outclk_1 : out std_logic         -- clk
		);
	end component PLL_main_altera_iopll_181_qm7lbwq_cmp;

	for iopll_0 : PLL_main_altera_iopll_181_qm7lbwq_cmp
		use entity altera_iopll_181.PLL_main_altera_iopll_181_qm7lbwq;
begin

	iopll_0 : component PLL_main_altera_iopll_181_qm7lbwq_cmp
		port map (
			rst      => rst,      --   reset.reset
			refclk   => refclk,   --  refclk.clk
			outclk_0 => outclk_0, -- outclk0.clk
			outclk_1 => outclk_1  -- outclk1.clk
		);

end architecture rtl; -- of PLL_main
