LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE WORK.COMPONENTS.ALL;

-- Need to set input range to 0V to 5.12V

ENTITY ADS8688 IS
	PORT(	CLOCK 				: IN STD_LOGIC;
			nRESET 				: IN STD_LOGIC;
	
			SDO 					: IN STD_LOGIC;
			FILTER_CONTROL		: IN STD_LOGIC_VECTOR(15 downto 0);		 
		 
			nCS 					: OUT STD_LOGIC;
			SCLK 					: OUT STD_LOGIC;
			SDI 					: OUT STD_LOGIC;
			DATA_OUT 			: OUT REG16_ARRAY
		 
		 );
END ENTITY ADS8688;

ARCHITECTURE BEHAVIOR OF ADS8688 IS

COMPONENT FILTERS IS
	PORT(	CLOCK 				: IN STD_LOGIC;
			STROBE				: IN STD_LOGIC;
			RESET 				: IN STD_LOGIC;
			FILTER_CONTROL		: IN STD_LOGIC_VECTOR(15 downto 0);
			DATA_IN 				: IN STD_LOGIC_VECTOR(15 downto 0);
			DATA_OUT 			: OUT STD_LOGIC_VECTOR(15 downto 0)
			);
END COMPONENT;

SIGNAL INP_DIN_REG	: STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL EN_DIN_REG		: STD_LOGIC;
SIGNAL LD_DIN_REG		: STD_LOGIC;
SIGNAL DIN				: STD_LOGIC;

SIGNAL CLR_DIN_CNT	: STD_LOGIC;
SIGNAL EN_DIN_CNT		: STD_LOGIC;
SIGNAL DIN_CNT			: STD_LOGIC_VECTOR(2 DOWNTO 0);

SIGNAL EN_SCLK_CNT	: STD_LOGIC;
SIGNAL SCLK_CNT		: STD_LOGIC_VECTOR(3 DOWNTO 0);

SIGNAL EN_BIT_CNT		: STD_LOGIC;
SIGNAL CLR_BIT_CNT	: STD_LOGIC;
SIGNAL BIT_CNT			: STD_LOGIC_VECTOR(4 DOWNTO 0);

SIGNAL SDO_BUF			: STD_LOGIC;
SIGNAL EN_DOUT			: STD_LOGIC;
SIGNAL DATA_BUF		: STD_LOGIC_VECTOR(31 DOWNTO 0);

SIGNAL SCLK_BUF		: STD_LOGIC;
SIGNAL nCS_BUF			: STD_LOGIC;
SIGNAL SDI_BUF			: STD_LOGIC;

SIGNAL EN_DATA_CHA		: STD_LOGIC;
SIGNAL EN_DATA_CHB		: STD_LOGIC;
SIGNAL EN_DATA_CHC		: STD_LOGIC;
SIGNAL EN_DATA_CHD		: STD_LOGIC;
SIGNAL EN_DATA_CHE		: STD_LOGIC;
SIGNAL EN_DATA_CHF		: STD_LOGIC;
SIGNAL EN_DATA_CHG		: STD_LOGIC;
SIGNAL EN_DATA_CHH		: STD_LOGIC;

SIGNAL DATA_CHA 			: STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL DATA_CHB 			: STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL DATA_CHC 			: STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL DATA_CHD 			: STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL DATA_CHE 			: STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL DATA_CHF 			: STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL DATA_CHG 			: STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL DATA_CHH 			: STD_LOGIC_VECTOR(15 DOWNTO 0);

SIGNAL INP_DIN_CTRL_REG	: STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL INP_DIN_RNG_REG	: STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL EN_CTRL_REG_SEL	: STD_LOGIC;
SIGNAL CTRL_REG_SEL		: STD_LOGIC;

SIGNAL EN_CTRL_RNG_CNT	: STD_LOGIC;
SIGNAL CTRL_RNG_CNT		: STD_LOGIC_VECTOR(2 DOWNTO 0);

TYPE STATE_TYPE IS (INIT, CS_LOW_RNG, CS_LOW_RNG_WAIT, CTRL_RNG_LD, CTRL_RNG_SCLK_HIGH, CTRL_RNG_SCLK_LOW, CTRL_RNG_CS_HIGH, CTRL_RNG_CS_HIGH_WAIT, CTRL_RNG_CS_HIGH_WAIT1, CS_LOW, CS_LOW_WAIT, CTRL_LD, CTRL_SCLK_HIGH, CTRL_SCLK_LOW, CS_HIGH, CS_HIGH_WAIT, CS_HIGH_WAIT1, CS_LOW_DATA, CS_LOW_DATA_WAIT, DATA_SCLK_HIGH, DATA_SCLK_LOW, CS_HIGH_DATA, CS_HIGH_DATA_WAIT, CS_HIGH_DATA_WAIT1, DATA_ACQ); 
SIGNAL STATE			: STATE_TYPE;

BEGIN
DATA_OUT(4)	<= DATA_CHA;
DATA_OUT(5)	<= DATA_CHB;
DATA_OUT(2)	<= DATA_CHC;
DATA_OUT(3)	<= DATA_CHD;
DATA_OUT(0)	<= DATA_CHE;
DATA_OUT(1)	<= DATA_CHF;
DATA_OUT(6)	<= DATA_CHG;
DATA_OUT(7)	<= DATA_CHH;

	
DATA_COUNTER: COUNTER
		GENERIC MAP(N => 3)
		PORT MAP(CLOCK		=> CLOCK,
			  	 RESET		=> nRESET,
			  	 CLEAR		=> '1',
			  	 ENABLE		=> EN_DIN_CNT,
			  	 COUNT		=> DIN_CNT
			 	 );
				 
CTRL_RNG_COUNTER: COUNTER
		GENERIC MAP(N => 3)
		PORT MAP(CLOCK		=> CLOCK,
			  	 RESET		=> nRESET,
			  	 CLEAR		=> '1',
			  	 ENABLE		=> EN_CTRL_RNG_CNT,
			  	 COUNT		=> CTRL_RNG_CNT
			 	 );

WITH DIN_CNT SELECT

	INP_DIN_CTRL_REG <= X"C400" WHEN "001",
						X"C800" WHEN "010",
						X"CC00" WHEN "011",
						X"D000" WHEN "100",
						X"D400" WHEN "101",
						X"D800" WHEN "110",
						X"DC00" WHEN "111",
						X"C000" WHEN OTHERS;
						
WITH CTRL_RNG_CNT SELECT

	INP_DIN_RNG_REG <= X"0D06" WHEN "001",
							 X"0F06" WHEN "010",
							 X"1106" WHEN "011",
							 X"1306" WHEN "100",
							 X"1506" WHEN "101",
							 X"1706" WHEN "110",
							 X"1906" WHEN "111",
							 X"0B06" WHEN OTHERS;
							 
INP_DIN_REG <= INP_DIN_CTRL_REG WHEN CTRL_REG_SEL = '1' ELSE INP_DIN_RNG_REG;
							 
							 
CTRL_REG_SEL_FF: FLIP_FLOP 
	PORT MAP(CLOCK	=> CLOCK,
		  	 RESET	=> nRESET,
		  	 CLEAR	=> '1',
		  	 EN		=> EN_CTRL_REG_SEL,
		  	 INP	=> '1',
		  	 OUP	=> CTRL_REG_SEL
		  	 );			   

ADC_DIN_REG: SHIFT_LEFT_REG_ADS8353
	GENERIC MAP(N => 16)
	PORT MAP(CLOCK	=> CLOCK,
		  	 RESET	=> nRESET,
		  	 EN		=> EN_DIN_REG,
		  	 LOAD	=> LD_DIN_REG,
		  	 INP	=> INP_DIN_REG,
		  	 OUTPUT	=> DIN
		  	 );
			   
SDI_FF: FLIP_FLOP 
	PORT MAP(CLOCK	=> CLOCK,
		  	 RESET	=> nRESET,
		  	 CLEAR	=> '1',
		  	 EN		=> '1',
		  	 INP	=> SDI_BUF,
		  	 OUP	=> SDI
		  	 );			   

SCLK_COUNTER: COUNTER
		GENERIC MAP(N => 4)
		PORT MAP(CLOCK		=> CLOCK,
			  	 RESET		=> nRESET,
			  	 CLEAR		=> '1',
			  	 ENABLE		=> EN_SCLK_CNT,
			  	 COUNT		=> SCLK_CNT
			 	 );
				  
SCLK_FF: FLIP_FLOP 
	PORT MAP(CLOCK	=> CLOCK,
		  	 RESET	=> nRESET,
		  	 CLEAR	=> '1',
		  	 EN		=> '1',
		  	 INP	=> SCLK_BUF,
		  	 OUP	=> SCLK
		  	 );
			   
nCS_FF: FLIP_FLOP 
	PORT MAP(CLOCK	=> CLOCK,
		  	 RESET	=> nRESET,
		  	 CLEAR	=> '1',
		  	 EN		=> '1',
		  	 INP	=> nCS_BUF,
		  	 OUP	=> nCS
		  	 );
			   
BIT_COUNTER: COUNTER
		GENERIC MAP(N => 5)
		PORT MAP(CLOCK		=> CLOCK,
			  	 RESET		=> nRESET,
			  	 CLEAR		=> CLR_BIT_CNT,
			  	 ENABLE		=> EN_BIT_CNT,
			  	 COUNT		=> BIT_CNT
			 	 );
				  
SDOA_FF: FLIP_FLOP 
	PORT MAP(CLOCK	=> CLOCK,
		  	 RESET	=> nRESET,
		  	 CLEAR	=> '1',
		  	 EN		=> '1',
		  	 INP	=> SDO,
		  	 OUP	=> SDO_BUF
		  	 );			   
				  
CONV_DATA_CHA: SHIFT_LEFT_REG
	GENERIC MAP(N => 32)
	PORT MAP(CLOCK	=> CLOCK,
		 	 RESET	=> nRESET,
		 	 EN		=> EN_DOUT,
		 	 INP	=> SDO_BUF,
		 	 OUTPUT	=> DATA_BUF
		 	 );
			  
CHA_DATA_BUF: REGNE
		GENERIC MAP(N => 16) 
		PORT MAP(CLOCK	=> CLOCK,
			  	 RESET	=> nRESET,
			  	 CLEAR	=> '1',
			  	 EN		=> EN_DATA_CHA,
			  	 INPUT	=> DATA_BUF(15 DOWNTO 0),
			  	 OUTPUT	=> DATA_CHA
				 );	

CHC_DATA_BUF: REGNE
		GENERIC MAP(N => 16) 
		PORT MAP(CLOCK	=> CLOCK,
			  	 RESET	=> nRESET,
			  	 CLEAR	=> '1',
			  	 EN		=> EN_DATA_CHC,
			  	 INPUT	=> DATA_BUF(15 DOWNTO 0),
			  	 OUTPUT	=> DATA_CHC
				 );
CHD_DATA_BUF: REGNE
		GENERIC MAP(N => 16) 
		PORT MAP(CLOCK	=> CLOCK,
			  	 RESET	=> nRESET,
			  	 CLEAR	=> '1',
			  	 EN		=> EN_DATA_CHD,
			  	 INPUT	=> DATA_BUF(15 DOWNTO 0),
			  	 OUTPUT	=> DATA_CHD
				 );
CHE_DATA_BUF: REGNE
		GENERIC MAP(N => 16) 
		PORT MAP(CLOCK	=> CLOCK,
			  	 RESET	=> nRESET,
			  	 CLEAR	=> '1',
			  	 EN		=> EN_DATA_CHE,
			  	 INPUT	=> DATA_BUF(15 DOWNTO 0),
			  	 OUTPUT	=> DATA_CHE
				 );	
CHF_DATA_BUF: REGNE
		GENERIC MAP(N => 16) 
		PORT MAP(CLOCK	=> CLOCK,
			  	 RESET	=> nRESET,
			  	 CLEAR	=> '1',
			  	 EN		=> EN_DATA_CHF,
			  	 INPUT	=> DATA_BUF(15 DOWNTO 0),
			  	 OUTPUT	=> DATA_CHF
				 );	
CHG_DATA_BUF: REGNE
		GENERIC MAP(N => 16) 
		PORT MAP(CLOCK	=> CLOCK,
			  	 RESET	=> nRESET,
			  	 CLEAR	=> '1',
			  	 EN		=> EN_DATA_CHG,
			  	 INPUT	=> DATA_BUF(15 DOWNTO 0),
			  	 OUTPUT	=> DATA_CHG
				 );	
CHH_DATA_BUF: REGNE
		GENERIC MAP(N => 16) 
		PORT MAP(CLOCK	=> CLOCK,
			  	 RESET	=> nRESET,
			  	 CLEAR	=> '1',
			  	 EN		=> EN_DATA_CHH,
			  	 INPUT	=> DATA_BUF(15 DOWNTO 0),
			  	 OUTPUT	=> DATA_CHH
				 );

----------------------------------------------------------------------------------
--Filtering ADC data before sending it out of the block.
----------------------------------------------------------------------------------

CHA_DATA_FILTER: FILTERS
		PORT MAP(CLOCK					=> CLOCK,
					STROBE				=> EN_DATA_CHA,
					RESET					=> nRESET,
					FILTER_CONTROL		=> FILTER_CONTROL,
					DATA_IN				=> DATA_BUF(15 DOWNTO 0),
					DATA_OUT				=> DATA_CHA
				 );
				
CHB_DATA_FILTER: FILTERS
		PORT MAP(CLOCK					=> CLOCK,
					STROBE				=> EN_DATA_CHB,
					RESET					=> nRESET,
					FILTER_CONTROL		=> FILTER_CONTROL,
					DATA_IN				=> DATA_BUF(15 DOWNTO 0),
					DATA_OUT				=> DATA_CHB
				 );	

CHC_DATA_FILTER: FILTERS
		PORT MAP(CLOCK					=> CLOCK,
					STROBE				=> EN_DATA_CHC,
					RESET					=> nRESET,
					FILTER_CONTROL		=> FILTER_CONTROL,
					DATA_IN				=> DATA_BUF(15 DOWNTO 0),
					DATA_OUT				=> DATA_CHC
				 );
CHD_DATA_FILTER: FILTERS
		PORT MAP(CLOCK					=> CLOCK,
					STROBE				=> EN_DATA_CHD,
					RESET					=> nRESET,
					FILTER_CONTROL		=> FILTER_CONTROL,
					DATA_IN					=> DATA_BUF(15 DOWNTO 0),
					DATA_OUT				=> DATA_CHD
				 );
CHE_DATA_FILTER: FILTERS
		PORT MAP(CLOCK					=> CLOCK,
					STROBE				=> EN_DATA_CHE,
					RESET					=> nRESET,
					FILTER_CONTROL		=> FILTER_CONTROL,
					DATA_IN					=> DATA_BUF(15 DOWNTO 0),
					DATA_OUT				=> DATA_CHE
				 );	
CHF_DATA_FILTER: FILTERS
		PORT MAP(CLOCK					=> CLOCK,
					STROBE				=> EN_DATA_CHF,
					RESET					=> nRESET,
					FILTER_CONTROL		=> FILTER_CONTROL,
					DATA_IN				=> DATA_BUF(15 DOWNTO 0),
					DATA_OUT				=> DATA_CHF
				 );	
CHG_DATA_FILTER: FILTERS
		PORT MAP(CLOCK					=> CLOCK,
					STROBE				=> EN_DATA_CHG,
					RESET					=> nRESET,
					FILTER_CONTROL		=> FILTER_CONTROL,
					DATA_IN				=> DATA_BUF(15 DOWNTO 0),
					DATA_OUT				=> DATA_CHG
				 );	
CHH_DATA_FILTER: FILTERS
		PORT MAP(CLOCK					=> CLOCK,
					STROBE				=> EN_DATA_CHH,
					RESET					=> nRESET,
					FILTER_CONTROL		=> FILTER_CONTROL,
					DATA_IN				=> DATA_BUF(15 DOWNTO 0),
					DATA_OUT				=> DATA_CHH
				 );
				 
				 
	PROCESS(CLOCK, nRESET)
	BEGIN
		IF nRESET = '0' THEN
			STATE <= INIT;
		ELSIF (CLOCK = '1' AND CLOCK' EVENT) THEN
			
			CASE STATE IS
				
				WHEN INIT				=> STATE <= CS_LOW_RNG;
				
				WHEN CS_LOW_RNG		=> STATE <= CS_LOW_RNG_WAIT;
				
				WHEN CS_LOW_RNG_WAIT	=> STATE <= CTRL_RNG_LD;
				
				WHEN CTRL_RNG_LD		=> STATE <= CTRL_RNG_SCLK_HIGH;
				
				WHEN CTRL_RNG_SCLK_HIGH	=> IF SCLK_CNT = "0111" THEN STATE <= CTRL_RNG_SCLK_LOW;
													ELSE STATE <= CTRL_RNG_SCLK_HIGH;
													END IF;
													
				WHEN CTRL_RNG_SCLK_LOW	=> IF SCLK_CNT = "1111" THEN
														IF BIT_CNT = "10111" THEN STATE <= CTRL_RNG_CS_HIGH;
														ELSE STATE <= CTRL_RNG_SCLK_HIGH;
														END IF;
													ELSE STATE <= CTRL_RNG_SCLK_LOW;
													END IF;
													
				WHEN CTRL_RNG_CS_HIGH	=> STATE <= CTRL_RNG_CS_HIGH_WAIT;
				
				WHEN CTRL_RNG_CS_HIGH_WAIT	=> STATE <= CTRL_RNG_CS_HIGH_WAIT1;
				
				WHEN CTRL_RNG_CS_HIGH_WAIT1	=> IF CTRL_RNG_CNT = "111" THEN STATE <= CS_LOW;
														ELSE STATE <= CS_LOW_RNG;
														END IF;				
				
				WHEN CS_LOW				=> STATE <= CS_LOW_WAIT;
				
				WHEN CS_LOW_WAIT		=> STATE <= CTRL_LD;
				
				WHEN CTRL_LD			=> STATE <= CTRL_SCLK_HIGH;
				
				WHEN CTRL_SCLK_HIGH		=> IF SCLK_CNT = "0111" THEN STATE <= CTRL_SCLK_LOW;
											ELSE STATE <= CTRL_SCLK_HIGH;
			  								END IF;
										  
				WHEN CTRL_SCLK_LOW		=> IF SCLK_CNT = "1111" THEN
												IF BIT_CNT = "11111" THEN STATE <= CS_HIGH;
												ELSE STATE <= CTRL_SCLK_HIGH;
												END IF;
											ELSE STATE <= CTRL_SCLK_LOW;
											END IF;
										
				WHEN CS_HIGH			=> STATE <= CS_HIGH_WAIT;
				
				WHEN CS_HIGH_WAIT		=> STATE <= CS_HIGH_WAIT1;

				WHEN CS_HIGH_WAIT1		=> STATE <= CS_LOW_DATA;
									   
				WHEN CS_LOW_DATA		=> STATE <= CS_LOW_DATA_WAIT;
				
				WHEN CS_LOW_DATA_WAIT	=> STATE <= DATA_SCLK_HIGH;
				
				WHEN DATA_SCLK_HIGH		=> IF SCLK_CNT = "0111" THEN STATE <= DATA_SCLK_LOW;
									  	 	ELSE STATE <= DATA_SCLK_HIGH;
									   		END IF;
									   
				WHEN DATA_SCLK_LOW		=> IF SCLK_CNT = "1111" THEN
												IF BIT_CNT = "11111" THEN STATE <= CS_HIGH_DATA;
										   		ELSE STATE <= DATA_SCLK_HIGH;
												END IF;
											ELSE STATE <= DATA_SCLK_LOW;
											END IF;
										
				WHEN CS_HIGH_DATA		=> STATE <= CS_HIGH_DATA_WAIT;
				
				WHEN CS_HIGH_DATA_WAIT	=> STATE <= CS_HIGH_DATA_WAIT1;
				
				WHEN CS_HIGH_DATA_WAIT1	=> STATE <= DATA_ACQ;
				
				WHEN DATA_ACQ			=> STATE <= CS_LOW;
				
				WHEN OTHERS				=> STATE <= INIT;
				
			END CASE;
		END IF;
	END PROCESS;
										   
												
SCLK_BUF	<= '0' WHEN STATE = DATA_SCLK_LOW OR STATE = CTRL_SCLK_LOW OR STATE = CTRL_RNG_SCLK_LOW ELSE '1';
EN_SCLK_CNT	<= '1' WHEN STATE = CTRL_SCLK_HIGH OR STATE = CTRL_SCLK_LOW OR STATE = DATA_SCLK_HIGH OR STATE = DATA_SCLK_LOW OR STATE = CTRL_RNG_SCLK_HIGH OR STATE = CTRL_RNG_SCLK_LOW ELSE '0';
	
EN_BIT_CNT	<= '1' WHEN (STATE = CTRL_SCLK_LOW OR STATE = DATA_SCLK_LOW OR STATE = CTRL_RNG_SCLK_LOW) AND SCLK_CNT = "1111" ELSE '0';
CLR_BIT_CNT	<= '0' WHEN STATE = CTRL_RNG_CS_HIGH ELSE '1';
	
EN_DIN_CNT	<= '1' WHEN STATE = DATA_ACQ ELSE '0';
	
nCS_BUF		<= '1' WHEN STATE = INIT OR STATE = CS_HIGH OR STATE = CS_HIGH_WAIT OR STATE = CS_HIGH_WAIT1 OR STATE = CS_HIGH_DATA OR STATE = CS_HIGH_DATA_WAIT OR STATE = CS_HIGH_DATA_WAIT1 OR STATE = DATA_ACQ OR STATE = CTRL_RNG_CS_HIGH OR STATE = CTRL_RNG_CS_HIGH_WAIT OR STATE = CTRL_RNG_CS_HIGH_WAIT1 ELSE '0';

LD_DIN_REG	<= '1' WHEN STATE = CTRL_LD OR STATE = CTRL_RNG_LD ELSE '0';
EN_DIN_REG	<= '1' WHEN (STATE = CTRL_SCLK_LOW OR STATE = CTRL_RNG_SCLK_LOW) AND SCLK_CNT = "1111" ELSE '0';	

EN_DATA_CHA	<= '1' WHEN (STATE = DATA_ACQ AND DIN_CNT = "000") ELSE '0';												
EN_DATA_CHB	<= '1' WHEN (STATE = DATA_ACQ AND DIN_CNT = "001") ELSE '0';
EN_DATA_CHC	<= '1' WHEN (STATE = DATA_ACQ AND DIN_CNT = "010") ELSE '0';
EN_DATA_CHD	<= '1' WHEN (STATE = DATA_ACQ AND DIN_CNT = "011") ELSE '0';	
EN_DATA_CHE	<= '1' WHEN (STATE = DATA_ACQ AND DIN_CNT = "100") ELSE '0';	
EN_DATA_CHF	<= '1' WHEN (STATE = DATA_ACQ AND DIN_CNT = "101") ELSE '0';	
EN_DATA_CHG	<= '1' WHEN (STATE = DATA_ACQ AND DIN_CNT = "110") ELSE '0';	
EN_DATA_CHH	<= '1' WHEN (STATE = DATA_ACQ AND DIN_CNT = "111") ELSE '0';	
												
EN_DOUT		<= '1' WHEN STATE = DATA_SCLK_HIGH AND SCLK_CNT = "0111" ELSE '0';
	
SDI_BUF		<= DIN WHEN STATE = CTRL_LD OR STATE = CTRL_SCLK_HIGH OR STATE = CTRL_SCLK_LOW OR STATE = CS_HIGH OR STATE = CS_HIGH_WAIT OR STATE = CTRL_RNG_LD OR STATE = CTRL_RNG_SCLK_HIGH OR STATE = CTRL_RNG_SCLK_LOW OR  STATE = CTRL_RNG_CS_HIGH OR STATE = CTRL_RNG_CS_HIGH_WAIT ELSE '0';

EN_CTRL_RNG_CNT <= '1' WHEN STATE = CTRL_RNG_CS_HIGH_WAIT1 ELSE '0';

EN_CTRL_REG_SEL <= '1' WHEN STATE = CS_LOW ELSE '0';	
	
END ARCHITECTURE BEHAVIOR;